### ISSUE TITLE
Please rename the app on Google Play

### ISSUE THREAD

**Issue by rectifyer** [Unbounds/trakt#16]
@maclir @effochka 

We’re working on our official Trakt Android app and I’d like to ask you to change the name of your app. This will allow us to name our app Trakt on Google Play so people clearly know it's the official app.

Thanks!

**Comment by rectifyer** [comment]
Google removed the listing.

**Comment by maclir** [comment]
@rectifyer great to hear that an official app is coming up on Android!
This app is no longer on the play store, but I will rename it before putting it up again.
